# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.py'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import gc
import sys
from typing import List
from os import path

from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QApplication, QStyleFactory
from window import MainWindow
from word import sensitiveWord
import os
import gc
import shutil

if __name__ == '__main__':
        app = QApplication(sys.argv)
        app.setStyle(QStyleFactory.create("Windows"))

        mainwindow = MainWindow()
        # mainwindow.setWindowOpacity(0.9)
        mainwindow.setObjectName("MainWindow")
        # mainwindow.setStyleSheet("#MainWindow{border-image:url(./image/1.jpg)}")
        mainwindow.setWindowIcon(QIcon('./image/3.ico'))
        mainwindow.show()

        sys.exit(app.exec_())


