# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.process = QtWidgets.QLabel(self.centralwidget)
        self.process.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process.sizePolicy().hasHeightForWidth())
        self.process.setSizePolicy(sizePolicy)
        self.process.setMinimumSize(QtCore.QSize(20, 30))
        self.process.setStyleSheet("\n"
"      QLabel{border:none;color:rgb(61, 61, 61);}\n"
"      QLabel{\n"
"        border:none;\n"
"        border-bottom:1px solid rgb(85, 170, 255);\n"
"        font-size:20px;\n"
"        font-weight:700;\n"
"        font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"      }\n"
"      QLabel:hover{border-left:4px solid rgb(85, 170, 255);font-weight:700;}")
        self.process.setAlignment(QtCore.Qt.AlignCenter)
        self.process.setObjectName("process")
        self.gridLayout.addWidget(self.process, 0, 3, 1, 1)
        self.showprocess = QtWidgets.QTextEdit(self.centralwidget)
        self.showprocess.setStyleSheet("QTextEdit{\n"
"border:1px groove gray;border-radius:6px;padding:1px 1px;border-style: outset;}")
        self.showprocess.setObjectName("showprocess")
        self.gridLayout.addWidget(self.showprocess, 1, 2, 1, 3)
        self.processdel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processdel.sizePolicy().hasHeightForWidth())
        self.processdel.setSizePolicy(sizePolicy)
        self.processdel.setMinimumSize(QtCore.QSize(0, 0))
        self.processdel.setStyleSheet("QPushButton{\n"
"background:rgb(174, 213, 255);\n"
"font-family:\'宋体\'; \n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;border-style: outset;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(176, 196, 222);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(135, 206, 250);\n"
"    padding-left:6px;\n"
"    padding-top:3px;\n"
"}")
        self.processdel.setObjectName("processdel")
        self.gridLayout.addWidget(self.processdel, 0, 4, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.generatefile = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generatefile.sizePolicy().hasHeightForWidth())
        self.generatefile.setSizePolicy(sizePolicy)
        self.generatefile.setMaximumSize(QtCore.QSize(16777215, 1777215))
        self.generatefile.setStyleSheet("QPushButton{\n"
"background:rgb(174, 213, 255);\n"
"font-family:\'宋体\'; \n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;border-style: outset;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(176, 196, 222);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(135, 206, 250);\n"
"    padding-left:6px;\n"
"    padding-top:3px;\n"
"}")
        self.generatefile.setIconSize(QtCore.QSize(24, 16))
        self.generatefile.setObjectName("generatefile")
        self.gridLayout_3.addWidget(self.generatefile, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.filterrun = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterrun.sizePolicy().hasHeightForWidth())
        self.filterrun.setSizePolicy(sizePolicy)
        self.filterrun.setStyleSheet("QPushButton{\n"
"background:rgb(174, 213, 255);\n"
"font-family:\'宋体\'; \n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;border-style: outset;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(176, 196, 222);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(135, 206, 250);\n"
"    padding-left:6px;\n"
"    padding-top:3px;\n"
"}")
        self.filterrun.setObjectName("filterrun")
        self.gridLayout_3.addWidget(self.filterrun, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.filterlabel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterlabel.sizePolicy().hasHeightForWidth())
        self.filterlabel.setSizePolicy(sizePolicy)
        self.filterlabel.setStyleSheet("\n"
"      QPushButton{border:none;color:rgb(61, 61, 61);}\n"
"      QPushButton{\n"
"        border:none;\n"
"        border-bottom:1px solid rgb(85, 170, 255);\n"
"        font-size:20px;\n"
"        font-weight:700;\n"
"        font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"      }\n"
"      QPushButton#left_button:hover{border-left:4px solid rgb(85, 170, 255);font-weight:700;}")
        self.filterlabel.setObjectName("filterlabel")
        self.gridLayout_3.addWidget(self.filterlabel, 0, 0, 1, 1)
        self.generaterun = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generaterun.sizePolicy().hasHeightForWidth())
        self.generaterun.setSizePolicy(sizePolicy)
        self.generaterun.setStyleSheet("QPushButton{\n"
"background:rgb(174, 213, 255);\n"
"font-family:\'宋体\'; \n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;border-style: outset;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(176, 196, 222);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(135, 206, 250);\n"
"    padding-left:6px;\n"
"    padding-top:3px;\n"
"}")
        self.generaterun.setObjectName("generaterun")
        self.gridLayout_3.addWidget(self.generaterun, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.generatelabel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generatelabel.sizePolicy().hasHeightForWidth())
        self.generatelabel.setSizePolicy(sizePolicy)
        self.generatelabel.setStyleSheet("\n"
"      QPushButton{border:none;color:rgb(61, 61, 61);}\n"
"      QPushButton{\n"
"        border:none;\n"
"        border-bottom:1px solid rgb(85, 170, 255);\n"
"        font-size:20px;\n"
"        font-weight:700;\n"
"        font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"      }\n"
"      QPushButton#left_button:hover{border-left:4px solid rgb(85, 170, 255);font-weight:700;}")
        self.generatelabel.setObjectName("generatelabel")
        self.gridLayout_3.addWidget(self.generatelabel, 3, 0, 1, 1)
        self.filterfile = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterfile.sizePolicy().hasHeightForWidth())
        self.filterfile.setSizePolicy(sizePolicy)
        self.filterfile.setStyleSheet("QPushButton{\n"
"background:rgb(174, 213, 255);\n"
"font-family:\'宋体\'; \n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;border-style: outset;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(176, 196, 222);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(135, 206, 250);\n"
"    padding-left:6px;\n"
"    padding-top:3px;\n"
"}\n"
"")
        self.filterfile.setObjectName("filterfile")
        self.gridLayout_3.addWidget(self.filterfile, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 4, 1)
        self.showresult = QtWidgets.QTextEdit(self.centralwidget)
        self.showresult.setStyleSheet("QTextEdit{\n"
"border:1px groove gray;border-radius:6px;padding:1px 1px;border-style: outset;}")
        self.showresult.setObjectName("showresult")
        self.gridLayout.addWidget(self.showresult, 3, 2, 1, 3)
        self.showfile = QtWidgets.QTextEdit(self.centralwidget)
        self.showfile.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.showfile.setStyleSheet("QTextEdit{\n"
"border:1px groove gray;border-radius:6px;padding:1px 1px;border-style: outset;}")
        self.showfile.setObjectName("showfile")
        self.gridLayout.addWidget(self.showfile, 0, 1, 4, 1)
        self.result = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result.sizePolicy().hasHeightForWidth())
        self.result.setSizePolicy(sizePolicy)
        self.result.setMinimumSize(QtCore.QSize(20, 30))
        self.result.setAutoFillBackground(False)
        self.result.setStyleSheet("QLabel{border:none;color:rgb(61, 61, 61);}\n"
"QLabel{\n"
"        border:none;\n"
"        border-bottom:1px solid rgb(85, 170, 255);\n"
"        font-size:20px;\n"
"        font-weight:700;\n"
"        font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;}\n"
"QLabel:hover{border-left:4px solid rgb(85, 170, 255);font-weight:700;}")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.gridLayout.addWidget(self.result, 2, 3, 1, 1)
        self.resultdel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultdel.sizePolicy().hasHeightForWidth())
        self.resultdel.setSizePolicy(sizePolicy)
        self.resultdel.setStyleSheet("QPushButton{\n"
"background:rgb(174, 213, 255);\n"
"font-family:\'宋体\'; \n"
"border:2px groove gray;border-radius:10px;padding:2px 4px;border-style: outset;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(176, 196, 222);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(135, 206, 250);\n"
"    padding-left:6px;\n"
"    padding-top:3px;\n"
"}")
        self.resultdel.setObjectName("resultdel")
        self.gridLayout.addWidget(self.resultdel, 2, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 530, 22))
        self.menubar.setObjectName("menubar")
        self.files = QtWidgets.QMenu(self.menubar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.files.sizePolicy().hasHeightForWidth())
        self.files.setSizePolicy(sizePolicy)
        self.files.setObjectName("files")
        self.logs = QtWidgets.QMenu(self.menubar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logs.sizePolicy().hasHeightForWidth())
        self.logs.setSizePolicy(sizePolicy)
        self.logs.setObjectName("logs")
        self.help = QtWidgets.QMenu(self.menubar)
        self.help.setObjectName("help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionclose = QtWidgets.QAction(MainWindow)
        self.actionclose.setObjectName("actionclose")
        self.logopen = QtWidgets.QAction(MainWindow)
        self.logopen.setObjectName("logopen")
        self.logclose = QtWidgets.QAction(MainWindow)
        self.logclose.setObjectName("logclose")
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.files.addAction(self.actionnew)
        self.files.addAction(self.actionopen)
        self.files.addAction(self.actionclose)
        self.files.addAction(self.actionsave)
        self.logs.addAction(self.logopen)
        self.logs.addAction(self.logclose)
        self.help.addAction(self.actionabout)
        self.menubar.addAction(self.files.menuAction())
        self.menubar.addAction(self.logs.menuAction())
        self.menubar.addAction(self.help.menuAction())

        self.retranslateUi(MainWindow)
        self.filterfile.clicked.connect(MainWindow.openfilterfile)
        self.filterrun.clicked.connect(MainWindow.openfilterrun)
        self.generatefile.clicked.connect(MainWindow.opengeneratefile)
        self.generaterun.clicked.connect(MainWindow.opengeneraterun)
        self.processdel.clicked.connect(MainWindow.openprocessdel)
        self.resultdel.clicked.connect(MainWindow.openresultdel)
        self.actionopen.triggered.connect(MainWindow.openactionopen)
        self.actionclose.triggered.connect(MainWindow.openactionclose)
        self.actionsave.triggered.connect(MainWindow.openactionsave)
        self.actionnew.triggered.connect(MainWindow.openactionclose)
        self.logopen.triggered.connect(MainWindow.openlogopen)
        self.logclose.triggered.connect(MainWindow.openactionclose)
        self.actionabout.triggered.connect(MainWindow.openlogabout)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.process.setText(_translate("MainWindow", "处理过程"))
        self.processdel.setText(_translate("MainWindow", "清空"))
        self.generatefile.setText(_translate("MainWindow", "查看词库"))
        self.filterrun.setText(_translate("MainWindow", "开始处理"))
        self.filterlabel.setText(_translate("MainWindow", "过滤"))
        self.generaterun.setText(_translate("MainWindow", "开始处理"))
        self.generatelabel.setText(_translate("MainWindow", "扩充"))
        self.filterfile.setText(_translate("MainWindow", "选择文件"))
        self.result.setText(_translate("MainWindow", "处理结果"))
        self.resultdel.setText(_translate("MainWindow", "清空"))
        self.files.setTitle(_translate("MainWindow", "文件"))
        self.logs.setTitle(_translate("MainWindow", "日志"))
        self.help.setTitle(_translate("MainWindow", "帮助"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionclose.setText(_translate("MainWindow", "close"))
        self.logopen.setText(_translate("MainWindow", "open"))
        self.logclose.setText(_translate("MainWindow", "close"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionabout.setText(_translate("MainWindow", "about"))
